/// Colegios con naturaleza y modelo pedagógico.
table dim_colegio
	lineageTag: 727b097d-68c3-4cb8-887d-f25983bb53f0

	column colegio_id
		dataType: int64
		isHidden
		lineageTag: 4a050d64-6d54-495d-a1bc-90fa0ae9e255
		sourceColumn: colegio_id

	column nombre_colegio
		dataType: string
		lineageTag: 287b1361-3cc5-40c3-b4f6-5f1becd5d09e
		sourceColumn: nombre_colegio

	column naturaleza_colegio
		dataType: string
		lineageTag: 45d0f2ff-20ab-4492-88ed-0917e10ae0a0
		sourceColumn: naturaleza_colegio

	column modelo_pedagogico
		dataType: string
		lineageTag: 3b4be363-609e-4397-834c-44014247a410
		sourceColumn: modelo_pedagogico

	partition dim_colegio = m
		mode: import
		source =
				let
				    Origen = Parquet.Document(File.Contents(RutaGold & "\dim_colegio.parquet")),
				    Tipos = Table.TransformColumnTypes(Origen, {{"colegio_id", Int64.Type}, {"nombre_colegio", type text}, {"naturaleza_colegio", type text}, {"modelo_pedagogico", type text}})
				in
				    Tipos

